import { sql } from 'drizzle-orm';
import { drizzle } from 'drizzle-orm/neon-http';
import { uuidv7 } from 'uuidv7';
import { env } from '@/config/env';
import * as schema from '@/db/schemas';

const db = drizzle(env.databaseUrl, { schema });

const daysAgo = (n: number): Date => {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d;
};

const hoursAgo = (n: number): Date => {
  const d = new Date();
  d.setHours(d.getHours() - n);
  return d;
};

const addMinutes = (date: Date, minutes: number): Date =>
  new Date(date.getTime() + minutes * 60_000);

const avatar = (seed: string) =>
  `https://api.dicebear.com/8.x/adventurer/svg?seed=${encodeURIComponent(seed)}&backgroundColor=b6e3f4,c0aede,d1d4f9,ffd5dc,ffdfbf`;

const USERS = [
  {
    id: uuidv7(),
    name: 'Lucas Mendonça',
    email: 'lucas.mendonca@example.com',
    emailVerified: true,
    image: avatar('lucas-mendonca'),
  },
  {
    id: uuidv7(),
    name: 'Fernanda Castro',
    email: 'fernanda.castro@example.com',
    emailVerified: true,
    image: avatar('fernanda-castro'),
  },
  {
    id: uuidv7(),
    name: 'Rafael Oliveira',
    email: 'rafael.oliveira@example.com',
    emailVerified: false,
    image: avatar('rafael-oliveira'),
  },
  {
    id: uuidv7(),
    name: 'Beatriz Lima',
    email: 'beatriz.lima@example.com',
    emailVerified: true,
    image: avatar('beatriz-lima'),
  },
] as const;

type WorkoutPlanInsert = {
  id: string;
  name: string;
  userId: string;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
};

type WorkoutDayInsert = {
  id: string;
  name: string;
  workoutPlanId: string;
  isRest: boolean;
  weekDay: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday';
  estimatedDurationInSeconds: number | null;
  coverImageUrl: string | null;
  createdAt: Date;
  updatedAt: Date;
};

type WorkoutExerciseInsert = {
  id: string;
  order: number;
  name: string;
  sets: number;
  reps: number;
  restTimeInSeconds: number;
  workoutDayId: string;
  createdAt: Date;
  updatedAt: Date;
};

type UserWorkoutSessionInsert = {
  id: string;
  userId: string;
  workoutDayId: string;
  startedAt: Date;
  completedAt: Date | null;
};

const workoutPlans: WorkoutPlanInsert[] = [
  {
    id: uuidv7(),
    name: 'PPL — Hipertrofia',
    userId: USERS[0].id,
    isActive: true,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },
  {
    id: uuidv7(),
    name: 'Full Body Iniciante',
    userId: USERS[0].id,
    isActive: false,
    createdAt: daysAgo(120),
    updatedAt: daysAgo(61),
  },
  {
    id: uuidv7(),
    name: 'Funcional Feminino',
    userId: USERS[1].id,
    isActive: true,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(2),
  },
  {
    id: uuidv7(),
    name: 'Powerlifting — Força Máxima',
    userId: USERS[2].id,
    isActive: true,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(10),
  },
  {
    id: uuidv7(),
    name: 'HIIT + Mobilidade',
    userId: USERS[3].id,
    isActive: true,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },
];

const [lucasPpl, , fernandaFuncional, rafaelPower, beatrizHiit] = workoutPlans;

const dayIds = {
  lucasPush: uuidv7(),
  lucasPull: uuidv7(),
  lucasLegs: uuidv7(),
  lucasRestThu: uuidv7(),
  lucasPush2: uuidv7(),
  lucasPull2: uuidv7(),
  lucasRestSun: uuidv7(),
  fernandaUpper: uuidv7(),
  fernandaLower: uuidv7(),
  fernandaCore: uuidv7(),
  fernandaRestThu: uuidv7(),
  fernandaCardio: uuidv7(),
  fernandaRestSat: uuidv7(),
  fernandaRestSun: uuidv7(),
  rafaelSquat: uuidv7(),
  rafaelBench: uuidv7(),
  rafaelRestWed: uuidv7(),
  rafaelDeadlift: uuidv7(),
  rafaelOhp: uuidv7(),
  rafaelRestSat: uuidv7(),
  rafaelRestSun: uuidv7(),
  beatrizHiit1: uuidv7(),
  beatrizMobility: uuidv7(),
  beatrizHiit2: uuidv7(),
  beatrizRestThu: uuidv7(),
  beatrizHiit3: uuidv7(),
  beatrizMobility2: uuidv7(),
  beatrizRestSun: uuidv7(),
};

const workoutDays: WorkoutDayInsert[] = [
  {
    id: dayIds.lucasPush,
    name: 'Push A — Peito, Ombro, Tríceps',
    workoutPlanId: lucasPpl.id,
    isRest: false,
    weekDay: 'monday',
    estimatedDurationInSeconds: 4200,
    coverImageUrl: 'https://gw8hy3fdcv.ufs.sh/f/ccoBDpLoAPCOgP9yzQkNGronCvXmSzAMs1N3KgLdE5yHT6Yk',
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },
  {
    id: dayIds.lucasPull,
    name: 'Pull A — Costas, Bíceps',
    workoutPlanId: lucasPpl.id,
    isRest: false,
    weekDay: 'tuesday',
    estimatedDurationInSeconds: 4200,
    coverImageUrl: 'https://gw8hy3fdcv.ufs.sh/f/ccoBDpLoAPCOgP9yzQkNGronCvXmSzAMs1N3KgLdE5yHT6Yk',
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },
  {
    id: dayIds.lucasLegs,
    name: 'Legs A — Quadríceps, Posterior',
    workoutPlanId: lucasPpl.id,
    isRest: false,
    weekDay: 'wednesday',
    coverImageUrl: 'https://gw8hy3fdcv.ufs.sh/f/ccoBDpLoAPCOgP9yzQkNGronCvXmSzAMs1N3KgLdE5yHT6Yk',
    estimatedDurationInSeconds: 4800,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },
  {
    id: dayIds.lucasRestThu,
    name: 'Descanso',
    workoutPlanId: lucasPpl.id,
    isRest: true,
    weekDay: 'thursday',
    coverImageUrl: 'https://gw8hy3fdcv.ufs.sh/f/ccoBDpLoAPCOgP9yzQkNGronCvXmSzAMs1N3KgLdE5yHT6Yk',
    estimatedDurationInSeconds: null,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },
  {
    id: dayIds.lucasPush2,
    name: 'Push B — Volume',
    workoutPlanId: lucasPpl.id,
    isRest: false,
    weekDay: 'friday',
    coverImageUrl: 'https://gw8hy3fdcv.ufs.sh/f/ccoBDpLoAPCOgP9yzQkNGronCvXmSzAMs1N3KgLdE5yHT6Yk',
    estimatedDurationInSeconds: 4500,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },
  {
    id: dayIds.lucasPull2,
    name: 'Pull B — Volume',
    workoutPlanId: lucasPpl.id,
    isRest: false,
    weekDay: 'saturday',
    coverImageUrl: 'https://gw8hy3fdcv.ufs.sh/f/ccoBDpLoAPCOgP9yzQkNGronCvXmSzAMs1N3KgLdE5yHT6Yk',
    estimatedDurationInSeconds: 4500,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },
  {
    id: dayIds.lucasRestSun,
    name: 'Descanso Ativo',
    workoutPlanId: lucasPpl.id,
    isRest: true,
    weekDay: 'sunday',
    coverImageUrl: 'https://gw8hy3fdcv.ufs.sh/f/ccoBDpLoAPCOgP9yzQkNGronCvXmSzAMs1N3KgLdE5yHT6Yk',
    estimatedDurationInSeconds: null,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },
  {
    id: dayIds.fernandaUpper,
    name: 'Upper Body Funcional',
    workoutPlanId: fernandaFuncional.id,
    isRest: false,
    weekDay: 'monday',
    coverImageUrl: 'https://gw8hy3fdcv.ufs.sh/f/ccoBDpLoAPCOgP9yzQkNGronCvXmSzAMs1N3KgLdE5yHT6Yk',
    estimatedDurationInSeconds: 3600,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(2),
  },
  {
    id: dayIds.fernandaLower,
    name: 'Lower Body + Glúteos',
    workoutPlanId: fernandaFuncional.id,
    isRest: false,
    weekDay: 'tuesday',
    coverImageUrl: 'https://gw8hy3fdcv.ufs.sh/f/ccoBDpLoAPCOgP9yzQkNGronCvXmSzAMs1N3KgLdE5yHT6Yk',
    estimatedDurationInSeconds: 3600,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(2),
  },
  {
    id: dayIds.fernandaCore,
    name: 'Core + Estabilização',
    workoutPlanId: fernandaFuncional.id,
    isRest: false,
    weekDay: 'wednesday',
    coverImageUrl: 'https://gw8hy3fdcv.ufs.sh/f/ccoBDpLoAPCOgP9yzQkNGronCvXmSzAMs1N3KgLdE5yHT6Yk',
    estimatedDurationInSeconds: 2700,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(2),
  },
  {
    id: dayIds.fernandaRestThu,
    name: 'Descanso',
    workoutPlanId: fernandaFuncional.id,
    isRest: true,
    weekDay: 'thursday',
    coverImageUrl: 'https://gw8hy3fdcv.ufs.sh/f/ccoBDpLoAPCOgP9yzQkNGronCvXmSzAMs1N3KgLdE5yHT6Yk',
    estimatedDurationInSeconds: null,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(2),
  },
  {
    id: dayIds.fernandaCardio,
    name: 'Cardio LISS + Alongamento',
    workoutPlanId: fernandaFuncional.id,
    isRest: false,
    weekDay: 'friday',
    coverImageUrl: 'https://gw8hy3fdcv.ufs.sh/f/ccoBDpLoAPCOgP9yzQkNGronCvXmSzAMs1N3KgLdE5yHT6Yk',
    estimatedDurationInSeconds: 3000,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(2),
  },
  {
    id: dayIds.fernandaRestSat,
    name: 'Descanso',
    workoutPlanId: fernandaFuncional.id,
    isRest: true,
    weekDay: 'saturday',
    coverImageUrl: 'https://gw8hy3fdcv.ufs.sh/f/ccoBDpLoAPCOgP9yzQkNGronCvXmSzAMs1N3KgLdE5yHT6Yk',
    estimatedDurationInSeconds: null,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(2),
  },
  {
    id: dayIds.fernandaRestSun,
    name: 'Descanso Ativo',
    workoutPlanId: fernandaFuncional.id,
    isRest: true,
    weekDay: 'sunday',
    coverImageUrl: 'https://gw8hy3fdcv.ufs.sh/f/ccoBDpLoAPCOgP9yzQkNGronCvXmSzAMs1N3KgLdE5yHT6Yk',
    estimatedDurationInSeconds: null,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(2),
  },
  {
    id: dayIds.rafaelSquat,
    name: 'Dia do Agachamento',
    workoutPlanId: rafaelPower.id,
    isRest: false,
    weekDay: 'monday',
    coverImageUrl: 'https://gw8hy3fdcv.ufs.sh/f/ccoBDpLoAPCOgP9yzQkNGronCvXmSzAMs1N3KgLdE5yHT6Yk',
    estimatedDurationInSeconds: 5400,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(10),
  },
  {
    id: dayIds.rafaelBench,
    name: 'Dia do Supino',
    workoutPlanId: rafaelPower.id,
    isRest: false,
    weekDay: 'tuesday',
    coverImageUrl: 'https://gw8hy3fdcv.ufs.sh/f/ccoBDpLoAPCOgP9yzQkNGronCvXmSzAMs1N3KgLdE5yHT6Yk',
    estimatedDurationInSeconds: 5400,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(10),
  },
  {
    id: dayIds.rafaelRestWed,
    name: 'Descanso',
    workoutPlanId: rafaelPower.id,
    isRest: true,
    weekDay: 'wednesday',
    coverImageUrl: 'https://gw8hy3fdcv.ufs.sh/f/ccoBDpLoAPCOgP9yzQkNGronCvXmSzAMs1N3KgLdE5yHT6Yk',
    estimatedDurationInSeconds: null,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(10),
  },
  {
    id: dayIds.rafaelDeadlift,
    name: 'Dia do Levantamento',
    workoutPlanId: rafaelPower.id,
    isRest: false,
    weekDay: 'thursday',
    coverImageUrl: 'https://gw8hy3fdcv.ufs.sh/f/ccoBDpLoAPCOgP9yzQkNGronCvXmSzAMs1N3KgLdE5yHT6Yk',
    estimatedDurationInSeconds: 5400,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(10),
  },
  {
    id: dayIds.rafaelOhp,
    name: 'Overhead Press + Acessórios',
    workoutPlanId: rafaelPower.id,
    isRest: false,
    weekDay: 'friday',
    coverImageUrl: 'https://gw8hy3fdcv.ufs.sh/f/ccoBDpLoAPCOgP9yzQkNGronCvXmSzAMs1N3KgLdE5yHT6Yk',
    estimatedDurationInSeconds: 4800,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(10),
  },
  {
    id: dayIds.rafaelRestSat,
    name: 'Descanso',
    workoutPlanId: rafaelPower.id,
    isRest: true,
    weekDay: 'saturday',
    coverImageUrl: 'https://gw8hy3fdcv.ufs.sh/f/ccoBDpLoAPCOgP9yzQkNGronCvXmSzAMs1N3KgLdE5yHT6Yk',
    estimatedDurationInSeconds: null,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(10),
  },
  {
    id: dayIds.rafaelRestSun,
    name: 'Descanso',
    workoutPlanId: rafaelPower.id,
    isRest: true,
    weekDay: 'sunday',
    coverImageUrl: 'https://gw8hy3fdcv.ufs.sh/f/ccoBDpLoAPCOgP9yzQkNGronCvXmSzAMs1N3KgLdE5yHT6Yk',
    estimatedDurationInSeconds: null,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(10),
  },
  {
    id: dayIds.beatrizHiit1,
    name: 'HIIT Metabólico',
    workoutPlanId: beatrizHiit.id,
    isRest: false,
    weekDay: 'monday',
    coverImageUrl: 'https://gw8hy3fdcv.ufs.sh/f/ccoBDpLoAPCOgP9yzQkNGronCvXmSzAMs1N3KgLdE5yHT6Yk',
    estimatedDurationInSeconds: 2400,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },
  {
    id: dayIds.beatrizMobility,
    name: 'Mobilidade + Yoga Flow',
    workoutPlanId: beatrizHiit.id,
    isRest: false,
    weekDay: 'tuesday',
    coverImageUrl: 'https://gw8hy3fdcv.ufs.sh/f/ccoBDpLoAPCOgP9yzQkNGronCvXmSzAMs1N3KgLdE5yHT6Yk',
    estimatedDurationInSeconds: 3000,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },
  {
    id: dayIds.beatrizHiit2,
    name: 'HIIT Inferior',
    workoutPlanId: beatrizHiit.id,
    isRest: false,
    weekDay: 'wednesday',
    coverImageUrl: 'https://gw8hy3fdcv.ufs.sh/f/ccoBDpLoAPCOgP9yzQkNGronCvXmSzAMs1N3KgLdE5yHT6Yk',
    estimatedDurationInSeconds: 2400,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },
  {
    id: dayIds.beatrizRestThu,
    name: 'Descanso',
    workoutPlanId: beatrizHiit.id,
    isRest: true,
    weekDay: 'thursday',
    coverImageUrl: 'https://gw8hy3fdcv.ufs.sh/f/ccoBDpLoAPCOgP9yzQkNGronCvXmSzAMs1N3KgLdE5yHT6Yk',
    estimatedDurationInSeconds: null,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },
  {
    id: dayIds.beatrizHiit3,
    name: 'HIIT Full Body',
    workoutPlanId: beatrizHiit.id,
    isRest: false,
    weekDay: 'friday',
    coverImageUrl: 'https://gw8hy3fdcv.ufs.sh/f/ccoBDpLoAPCOgP9yzQkNGronCvXmSzAMs1N3KgLdE5yHT6Yk',
    estimatedDurationInSeconds: 2700,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },
  {
    id: dayIds.beatrizMobility2,
    name: 'Mobilidade Profunda',
    workoutPlanId: beatrizHiit.id,
    isRest: false,
    weekDay: 'saturday',
    coverImageUrl: 'https://gw8hy3fdcv.ufs.sh/f/ccoBDpLoAPCOgP9yzQkNGronCvXmSzAMs1N3KgLdE5yHT6Yk',
    estimatedDurationInSeconds: 3600,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },
  {
    id: dayIds.beatrizRestSun,
    name: 'Descanso Ativo',
    workoutPlanId: beatrizHiit.id,
    isRest: true,
    weekDay: 'sunday',
    coverImageUrl: 'https://gw8hy3fdcv.ufs.sh/f/ccoBDpLoAPCOgP9yzQkNGronCvXmSzAMs1N3KgLdE5yHT6Yk',
    estimatedDurationInSeconds: null,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },
];

const workoutExercises: WorkoutExerciseInsert[] = [
  {
    id: uuidv7(),
    order: 1,
    name: 'Supino Reto com Barra',
    sets: 4,
    reps: 8,
    restTimeInSeconds: 180,
    workoutDayId: dayIds.lucasPush,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },
  {
    id: uuidv7(),
    order: 2,
    name: 'Supino Inclinado com Halteres',
    sets: 3,
    reps: 10,
    restTimeInSeconds: 120,
    workoutDayId: dayIds.lucasPush,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },
  {
    id: uuidv7(),
    order: 3,
    name: 'Desenvolvimento com Barra',
    sets: 4,
    reps: 8,
    restTimeInSeconds: 180,
    workoutDayId: dayIds.lucasPush,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },
  {
    id: uuidv7(),
    order: 4,
    name: 'Elevação Lateral com Halteres',
    sets: 4,
    reps: 15,
    restTimeInSeconds: 60,
    workoutDayId: dayIds.lucasPush,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },
  {
    id: uuidv7(),
    order: 5,
    name: 'Tríceps Pulley',
    sets: 3,
    reps: 12,
    restTimeInSeconds: 90,
    workoutDayId: dayIds.lucasPush,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },
  {
    id: uuidv7(),
    order: 6,
    name: 'Tríceps Francês com Haltere',
    sets: 3,
    reps: 12,
    restTimeInSeconds: 90,
    workoutDayId: dayIds.lucasPush,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },
  {
    id: uuidv7(),
    order: 1,
    name: 'Puxada Frontal com Triângulo',
    sets: 4,
    reps: 8,
    restTimeInSeconds: 180,
    workoutDayId: dayIds.lucasPull,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },
  {
    id: uuidv7(),
    order: 2,
    name: 'Remada Curvada com Barra',
    sets: 4,
    reps: 8,
    restTimeInSeconds: 180,
    workoutDayId: dayIds.lucasPull,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },
  {
    id: uuidv7(),
    order: 3,
    name: 'Remada Unilateral com Halter',
    sets: 3,
    reps: 10,
    restTimeInSeconds: 120,
    workoutDayId: dayIds.lucasPull,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },
  {
    id: uuidv7(),
    order: 4,
    name: 'Rosca Direta com Barra',
    sets: 4,
    reps: 10,
    restTimeInSeconds: 90,
    workoutDayId: dayIds.lucasPull,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },
  {
    id: uuidv7(),
    order: 5,
    name: 'Rosca Martelo com Halteres',
    sets: 3,
    reps: 12,
    restTimeInSeconds: 75,
    workoutDayId: dayIds.lucasPull,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },
  {
    id: uuidv7(),
    order: 6,
    name: 'Face Pull com Corda',
    sets: 3,
    reps: 15,
    restTimeInSeconds: 60,
    workoutDayId: dayIds.lucasPull,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },
  {
    id: uuidv7(),
    order: 1,
    name: 'Agachamento Livre com Barra',
    sets: 5,
    reps: 5,
    restTimeInSeconds: 240,
    workoutDayId: dayIds.lucasLegs,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },
  {
    id: uuidv7(),
    order: 2,
    name: 'Leg Press 45°',
    sets: 4,
    reps: 10,
    restTimeInSeconds: 180,
    workoutDayId: dayIds.lucasLegs,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },
  {
    id: uuidv7(),
    order: 3,
    name: 'Cadeira Extensora',
    sets: 3,
    reps: 12,
    restTimeInSeconds: 90,
    workoutDayId: dayIds.lucasLegs,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },
  {
    id: uuidv7(),
    order: 4,
    name: 'Mesa Flexora',
    sets: 3,
    reps: 12,
    restTimeInSeconds: 90,
    workoutDayId: dayIds.lucasLegs,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },
  {
    id: uuidv7(),
    order: 5,
    name: 'Stiff com Halteres',
    sets: 3,
    reps: 10,
    restTimeInSeconds: 120,
    workoutDayId: dayIds.lucasLegs,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },
  {
    id: uuidv7(),
    order: 6,
    name: 'Panturrilha em Pé na Máquina',
    sets: 5,
    reps: 15,
    restTimeInSeconds: 60,
    workoutDayId: dayIds.lucasLegs,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },
  {
    id: uuidv7(),
    order: 1,
    name: 'Supino Inclinado com Barra',
    sets: 4,
    reps: 10,
    restTimeInSeconds: 150,
    workoutDayId: dayIds.lucasPush2,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },
  {
    id: uuidv7(),
    order: 2,
    name: 'Crossover no Cabo',
    sets: 3,
    reps: 15,
    restTimeInSeconds: 90,
    workoutDayId: dayIds.lucasPush2,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },
  {
    id: uuidv7(),
    order: 3,
    name: 'Arnold Press com Halteres',
    sets: 4,
    reps: 10,
    restTimeInSeconds: 120,
    workoutDayId: dayIds.lucasPush2,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },
  {
    id: uuidv7(),
    order: 4,
    name: 'Elevação Frontal com Disco',
    sets: 3,
    reps: 12,
    restTimeInSeconds: 75,
    workoutDayId: dayIds.lucasPush2,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },
  {
    id: uuidv7(),
    order: 5,
    name: 'Tríceps Mergulho no Banco',
    sets: 3,
    reps: 15,
    restTimeInSeconds: 75,
    workoutDayId: dayIds.lucasPush2,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },
  {
    id: uuidv7(),
    order: 1,
    name: 'Barra Fixa Pronada',
    sets: 4,
    reps: 8,
    restTimeInSeconds: 180,
    workoutDayId: dayIds.lucasPull2,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },
  {
    id: uuidv7(),
    order: 2,
    name: 'Serrote com Halter',
    sets: 4,
    reps: 10,
    restTimeInSeconds: 120,
    workoutDayId: dayIds.lucasPull2,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },
  {
    id: uuidv7(),
    order: 3,
    name: 'Pullover na Polia',
    sets: 3,
    reps: 12,
    restTimeInSeconds: 90,
    workoutDayId: dayIds.lucasPull2,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },
  {
    id: uuidv7(),
    order: 4,
    name: 'Rosca Concentrada',
    sets: 3,
    reps: 12,
    restTimeInSeconds: 75,
    workoutDayId: dayIds.lucasPull2,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },
  {
    id: uuidv7(),
    order: 5,
    name: 'Rosca 21',
    sets: 3,
    reps: 21,
    restTimeInSeconds: 90,
    workoutDayId: dayIds.lucasPull2,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },
  {
    id: uuidv7(),
    order: 1,
    name: 'Flexão de Braço com Variação',
    sets: 4,
    reps: 10,
    restTimeInSeconds: 90,
    workoutDayId: dayIds.fernandaUpper,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(2),
  },
  {
    id: uuidv7(),
    order: 2,
    name: 'Remada com Elástico',
    sets: 3,
    reps: 15,
    restTimeInSeconds: 75,
    workoutDayId: dayIds.fernandaUpper,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(2),
  },
  {
    id: uuidv7(),
    order: 3,
    name: 'Desenvolvimento com Halteres',
    sets: 3,
    reps: 12,
    restTimeInSeconds: 90,
    workoutDayId: dayIds.fernandaUpper,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(2),
  },
  {
    id: uuidv7(),
    order: 4,
    name: 'Superman no Chão',
    sets: 3,
    reps: 15,
    restTimeInSeconds: 60,
    workoutDayId: dayIds.fernandaUpper,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(2),
  },
  {
    id: uuidv7(),
    order: 5,
    name: 'Bird Dog',
    sets: 3,
    reps: 12,
    restTimeInSeconds: 60,
    workoutDayId: dayIds.fernandaUpper,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(2),
  },
  {
    id: uuidv7(),
    order: 1,
    name: 'Agachamento Sumô com Halter',
    sets: 4,
    reps: 15,
    restTimeInSeconds: 90,
    workoutDayId: dayIds.fernandaLower,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(2),
  },
  {
    id: uuidv7(),
    order: 2,
    name: 'Levantamento Terra Romeno',
    sets: 4,
    reps: 12,
    restTimeInSeconds: 120,
    workoutDayId: dayIds.fernandaLower,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(2),
  },
  {
    id: uuidv7(),
    order: 3,
    name: 'Hip Thrust com Barra',
    sets: 4,
    reps: 15,
    restTimeInSeconds: 120,
    workoutDayId: dayIds.fernandaLower,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(2),
  },
  {
    id: uuidv7(),
    order: 4,
    name: 'Afundo com Halteres',
    sets: 3,
    reps: 12,
    restTimeInSeconds: 90,
    workoutDayId: dayIds.fernandaLower,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(2),
  },
  {
    id: uuidv7(),
    order: 5,
    name: 'Abdução no Cabo',
    sets: 3,
    reps: 20,
    restTimeInSeconds: 60,
    workoutDayId: dayIds.fernandaLower,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(2),
  },
  {
    id: uuidv7(),
    order: 6,
    name: 'Elevação Pélvica Unilateral',
    sets: 3,
    reps: 15,
    restTimeInSeconds: 60,
    workoutDayId: dayIds.fernandaLower,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(2),
  },
  {
    id: uuidv7(),
    order: 1,
    name: 'Prancha Frontal',
    sets: 4,
    reps: 1,
    restTimeInSeconds: 60,
    workoutDayId: dayIds.fernandaCore,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(2),
  },
  {
    id: uuidv7(),
    order: 2,
    name: 'Abdominal Bicicleta',
    sets: 3,
    reps: 20,
    restTimeInSeconds: 60,
    workoutDayId: dayIds.fernandaCore,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(2),
  },
  {
    id: uuidv7(),
    order: 3,
    name: 'Dead Bug',
    sets: 3,
    reps: 10,
    restTimeInSeconds: 75,
    workoutDayId: dayIds.fernandaCore,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(2),
  },
  {
    id: uuidv7(),
    order: 4,
    name: 'Russian Twist com Peso',
    sets: 3,
    reps: 20,
    restTimeInSeconds: 60,
    workoutDayId: dayIds.fernandaCore,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(2),
  },
  {
    id: uuidv7(),
    order: 5,
    name: 'Hollow Body Hold',
    sets: 3,
    reps: 1,
    restTimeInSeconds: 60,
    workoutDayId: dayIds.fernandaCore,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(2),
  },
  {
    id: uuidv7(),
    order: 1,
    name: 'Agachamento Livre (Squat) 5x5',
    sets: 5,
    reps: 5,
    restTimeInSeconds: 300,
    workoutDayId: dayIds.rafaelSquat,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(10),
  },
  {
    id: uuidv7(),
    order: 2,
    name: 'Agachamento Pausa 3s',
    sets: 3,
    reps: 3,
    restTimeInSeconds: 300,
    workoutDayId: dayIds.rafaelSquat,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(10),
  },
  {
    id: uuidv7(),
    order: 3,
    name: 'Leg Press Alta',
    sets: 4,
    reps: 8,
    restTimeInSeconds: 180,
    workoutDayId: dayIds.rafaelSquat,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(10),
  },
  {
    id: uuidv7(),
    order: 4,
    name: 'Avanço com Barra',
    sets: 3,
    reps: 8,
    restTimeInSeconds: 120,
    workoutDayId: dayIds.rafaelSquat,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(10),
  },
  {
    id: uuidv7(),
    order: 5,
    name: 'Panturrilha Sentado',
    sets: 5,
    reps: 15,
    restTimeInSeconds: 60,
    workoutDayId: dayIds.rafaelSquat,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(10),
  },
  {
    id: uuidv7(),
    order: 1,
    name: 'Supino Reto (Bench Press) 5x5',
    sets: 5,
    reps: 5,
    restTimeInSeconds: 300,
    workoutDayId: dayIds.rafaelBench,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(10),
  },
  {
    id: uuidv7(),
    order: 2,
    name: 'Supino com Pausa no Peito',
    sets: 3,
    reps: 3,
    restTimeInSeconds: 300,
    workoutDayId: dayIds.rafaelBench,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(10),
  },
  {
    id: uuidv7(),
    order: 3,
    name: 'Supino Inclinado com Barra',
    sets: 3,
    reps: 8,
    restTimeInSeconds: 180,
    workoutDayId: dayIds.rafaelBench,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(10),
  },
  {
    id: uuidv7(),
    order: 4,
    name: 'Tríceps Pulley Corda',
    sets: 4,
    reps: 10,
    restTimeInSeconds: 90,
    workoutDayId: dayIds.rafaelBench,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(10),
  },
  {
    id: uuidv7(),
    order: 5,
    name: 'Elevação Lateral Cabos',
    sets: 3,
    reps: 15,
    restTimeInSeconds: 75,
    workoutDayId: dayIds.rafaelBench,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(10),
  },
  {
    id: uuidv7(),
    order: 1,
    name: 'Levantamento Terra Convencional',
    sets: 4,
    reps: 4,
    restTimeInSeconds: 360,
    workoutDayId: dayIds.rafaelDeadlift,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(10),
  },
  {
    id: uuidv7(),
    order: 2,
    name: 'Terra Romeno com Barra',
    sets: 3,
    reps: 6,
    restTimeInSeconds: 240,
    workoutDayId: dayIds.rafaelDeadlift,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(10),
  },
  {
    id: uuidv7(),
    order: 3,
    name: 'Puxada Frontal Aberta',
    sets: 4,
    reps: 8,
    restTimeInSeconds: 150,
    workoutDayId: dayIds.rafaelDeadlift,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(10),
  },
  {
    id: uuidv7(),
    order: 4,
    name: 'Remada Cavalinho',
    sets: 3,
    reps: 8,
    restTimeInSeconds: 150,
    workoutDayId: dayIds.rafaelDeadlift,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(10),
  },
  {
    id: uuidv7(),
    order: 5,
    name: 'Flexão de Quadril na Polia Baixa',
    sets: 3,
    reps: 12,
    restTimeInSeconds: 90,
    workoutDayId: dayIds.rafaelDeadlift,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(10),
  },
  {
    id: uuidv7(),
    order: 1,
    name: 'Desenvolvimento Militar com Barra',
    sets: 5,
    reps: 5,
    restTimeInSeconds: 300,
    workoutDayId: dayIds.rafaelOhp,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(10),
  },
  {
    id: uuidv7(),
    order: 2,
    name: 'Push Press',
    sets: 3,
    reps: 5,
    restTimeInSeconds: 240,
    workoutDayId: dayIds.rafaelOhp,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(10),
  },
  {
    id: uuidv7(),
    order: 3,
    name: 'Elevação Lateral 3x15',
    sets: 3,
    reps: 15,
    restTimeInSeconds: 75,
    workoutDayId: dayIds.rafaelOhp,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(10),
  },
  {
    id: uuidv7(),
    order: 4,
    name: 'Rosca Direta com Barra',
    sets: 3,
    reps: 8,
    restTimeInSeconds: 120,
    workoutDayId: dayIds.rafaelOhp,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(10),
  },
  {
    id: uuidv7(),
    order: 5,
    name: 'Encolhimento com Barra',
    sets: 4,
    reps: 12,
    restTimeInSeconds: 90,
    workoutDayId: dayIds.rafaelOhp,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(10),
  },
  {
    id: uuidv7(),
    order: 1,
    name: 'Burpee',
    sets: 5,
    reps: 10,
    restTimeInSeconds: 30,
    workoutDayId: dayIds.beatrizHiit1,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },
  {
    id: uuidv7(),
    order: 2,
    name: 'Agachamento com Salto',
    sets: 4,
    reps: 15,
    restTimeInSeconds: 30,
    workoutDayId: dayIds.beatrizHiit1,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },
  {
    id: uuidv7(),
    order: 3,
    name: 'Mountain Climber',
    sets: 4,
    reps: 20,
    restTimeInSeconds: 30,
    workoutDayId: dayIds.beatrizHiit1,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },
  {
    id: uuidv7(),
    order: 4,
    name: 'Polichinelo',
    sets: 3,
    reps: 30,
    restTimeInSeconds: 20,
    workoutDayId: dayIds.beatrizHiit1,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },
  {
    id: uuidv7(),
    order: 5,
    name: 'Sprint Estacionário',
    sets: 5,
    reps: 1,
    restTimeInSeconds: 45,
    workoutDayId: dayIds.beatrizHiit1,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },
  {
    id: uuidv7(),
    order: 1,
    name: 'Cat-Cow Espinha',
    sets: 3,
    reps: 10,
    restTimeInSeconds: 30,
    workoutDayId: dayIds.beatrizMobility,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },
  {
    id: uuidv7(),
    order: 2,
    name: 'Hip 90/90 Rotação',
    sets: 3,
    reps: 8,
    restTimeInSeconds: 30,
    workoutDayId: dayIds.beatrizMobility,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },
  {
    id: uuidv7(),
    order: 3,
    name: 'Abertura de Quadril Baixo',
    sets: 3,
    reps: 5,
    restTimeInSeconds: 45,
    workoutDayId: dayIds.beatrizMobility,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },
  {
    id: uuidv7(),
    order: 4,
    name: 'Alongamento de Piriforme',
    sets: 3,
    reps: 1,
    restTimeInSeconds: 30,
    workoutDayId: dayIds.beatrizMobility,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },
  {
    id: uuidv7(),
    order: 5,
    name: 'Thread the Needle',
    sets: 3,
    reps: 8,
    restTimeInSeconds: 30,
    workoutDayId: dayIds.beatrizMobility,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },
  {
    id: uuidv7(),
    order: 1,
    name: 'Agachamento Sumô com Salto',
    sets: 4,
    reps: 12,
    restTimeInSeconds: 30,
    workoutDayId: dayIds.beatrizHiit2,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },
  {
    id: uuidv7(),
    order: 2,
    name: 'Step Up com Joelho Alto',
    sets: 4,
    reps: 15,
    restTimeInSeconds: 30,
    workoutDayId: dayIds.beatrizHiit2,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },
  {
    id: uuidv7(),
    order: 3,
    name: 'Afundo com Salto Alternado',
    sets: 4,
    reps: 10,
    restTimeInSeconds: 30,
    workoutDayId: dayIds.beatrizHiit2,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },
  {
    id: uuidv7(),
    order: 4,
    name: 'Glute Kickback',
    sets: 3,
    reps: 20,
    restTimeInSeconds: 30,
    workoutDayId: dayIds.beatrizHiit2,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },
  {
    id: uuidv7(),
    order: 1,
    name: 'Circuito Tabata — Flexão',
    sets: 8,
    reps: 1,
    restTimeInSeconds: 10,
    workoutDayId: dayIds.beatrizHiit3,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },
  {
    id: uuidv7(),
    order: 2,
    name: 'Circuito Tabata — Agachamento',
    sets: 8,
    reps: 1,
    restTimeInSeconds: 10,
    workoutDayId: dayIds.beatrizHiit3,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },
  {
    id: uuidv7(),
    order: 3,
    name: 'Circuito Tabata — Burpee',
    sets: 8,
    reps: 1,
    restTimeInSeconds: 10,
    workoutDayId: dayIds.beatrizHiit3,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },
  {
    id: uuidv7(),
    order: 4,
    name: 'Cool Down — Respiração 4-7-8',
    sets: 3,
    reps: 4,
    restTimeInSeconds: 0,
    workoutDayId: dayIds.beatrizHiit3,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },
];

const buildSessions = (): UserWorkoutSessionInsert[] => {
  const sessions: UserWorkoutSessionInsert[] = [];

  const lucasDayRotation = [
    dayIds.lucasPush,
    dayIds.lucasPull,
    dayIds.lucasLegs,
    dayIds.lucasPush2,
    dayIds.lucasPull2,
  ];
  const lucasDurations = [4100, 4350, 4700, 4400, 4300];
  [0, 1, 2, 4, 5, 7, 8, 9, 11, 12, 14, 15, 16, 18, 19, 21, 22].forEach((daysBack, i) => {
    const dayIndex = i % lucasDayRotation.length;
    const started = hoursAgo(daysBack * 24 + 18);
    sessions.push({
      id: uuidv7(),
      userId: USERS[0].id,
      workoutDayId: lucasDayRotation[dayIndex],
      startedAt: started,
      completedAt: addMinutes(started, Math.floor(lucasDurations[dayIndex] / 60)),
    });
  });

  const fernandaDayRotation = [
    dayIds.fernandaUpper,
    dayIds.fernandaLower,
    dayIds.fernandaCore,
    dayIds.fernandaCardio,
  ];
  const fernandaDurations = [55, 58, 43, 48];
  [0, 2, 4, 7, 9, 11, 14, 16, 18, 21, 23].forEach((daysBack, i) => {
    const dayIndex = i % fernandaDayRotation.length;
    const started = hoursAgo(daysBack * 24 + 19);
    sessions.push({
      id: uuidv7(),
      userId: USERS[1].id,
      workoutDayId: fernandaDayRotation[dayIndex],
      startedAt: started,
      completedAt: addMinutes(started, fernandaDurations[dayIndex]),
    });
  });

  const rafaelDayRotation = [
    dayIds.rafaelSquat,
    dayIds.rafaelBench,
    dayIds.rafaelDeadlift,
    dayIds.rafaelOhp,
  ];
  const rafaelDurations = [88, 85, 92, 78];
  [0, 1, 3, 4, 7, 8, 10, 11, 14, 15, 17, 18, 21, 22, 24, 25].forEach((daysBack, i) => {
    const dayIndex = i % rafaelDayRotation.length;
    const started = hoursAgo(daysBack * 24 + 17);
    sessions.push({
      id: uuidv7(),
      userId: USERS[2].id,
      workoutDayId: rafaelDayRotation[dayIndex],
      startedAt: started,
      completedAt: addMinutes(started, rafaelDurations[dayIndex]),
    });
  });

  const beatrizDayRotation = [
    dayIds.beatrizHiit1,
    dayIds.beatrizMobility,
    dayIds.beatrizHiit2,
    dayIds.beatrizHiit3,
    dayIds.beatrizMobility2,
  ];
  const beatrizDurations = [38, 48, 37, 42, 58];
  [0, 2, 4, 7, 9, 11].forEach((daysBack, i) => {
    const dayIndex = i % beatrizDayRotation.length;
    const started = hoursAgo(daysBack * 24 + 7);
    sessions.push({
      id: uuidv7(),
      userId: USERS[3].id,
      workoutDayId: beatrizDayRotation[dayIndex],
      startedAt: started,
      completedAt: addMinutes(started, beatrizDurations[dayIndex]),
    });
  });

  sessions.push({
    id: uuidv7(),
    userId: USERS[0].id,
    workoutDayId: dayIds.lucasPush,
    startedAt: hoursAgo(1),
    completedAt: null,
  });

  return sessions;
};

async function seed() {
  console.log('🗑️ Limpando banco...');
  await db.execute(sql`
      TRUNCATE TABLE "workout_exercises", "workout_days", "workout_plans", 
                     "user_workout_sessions", "session", "account", 
                     "verification", "user" 
      RESTART IDENTITY CASCADE;
    `);
  console.log('🌱 Iniciando seed...');
  console.log('👥 Inserindo usuários...');
  await db.insert(schema.user).values(
    USERS.map((u) => ({
      ...u,
      createdAt: daysAgo(Math.floor(Math.random() * 90) + 30),
      updatedAt: daysAgo(Math.floor(Math.random() * 5)),
    })),
  );
  console.log(`   ✓ ${USERS.length} usuários inseridos`);
  console.log('📋 Inserindo planos de treino...');
  await db.insert(schema.workoutPlans).values(workoutPlans);
  console.log(`   ✓ ${workoutPlans.length} planos inseridos`);
  console.log('📅 Inserindo dias de treino...');
  await db.insert(schema.workoutDays).values(workoutDays);
  console.log(`   ✓ ${workoutDays.length} dias inseridos`);
  console.log('🏋️  Inserindo exercícios...');
  await db.insert(schema.workoutExercises).values(workoutExercises);
  console.log(`   ✓ ${workoutExercises.length} exercícios inseridos`);
  const sessions = buildSessions();
  console.log('⏱️  Inserindo sessões...');
  await db.insert(schema.userWorkoutSessions).values(sessions);
  console.log(`   ✓ ${sessions.length} sessões inseridas`);
  console.log('✅ Seed concluído com sucesso!');
  console.log(`📊 Resumo:
• ${USERS.length} usuários (4 perfis: hipertrofia / funcional / powerlifting / HIIT)
• ${workoutPlans.length} planos de treino (1 inativo para histórico)
• ${workoutDays.length} dias de treino (descansos inclusos)
• ${workoutExercises.length} exercícios com séries/reps/descanso realistas
• ${sessions.length} sessões (últimas 4 semanas + 1 ativa)
`);
}

seed().catch((err) => {
  console.error('❌ Seed falhou:', err);
  process.exit(1);
});
